solution
mate-academy/react_carousel pull request #132
Opened 2022-03-27 09:12 UTC by SanyaBratashchuk

[DEMO LINK](https://SanyaBratashchuk.github.io/react_carousel/)

2022-03-29 04:42 UTC, jstmpelowycz commented on src/App.tsx
> +    } = this.state;
```suggestion
    const { images } = this.state;
```

2022-03-29 04:43 UTC, jstmpelowycz commented on src/App.tsx
> +        />
```suggestion
        <Carousel images={images} />
```

2022-03-29 04:46 UTC, jstmpelowycz commented on src/components/Carousel.tsx
> +    itemWidth: 140,
Why `140` but not `130` as required? I would recommend you to change it
I encountered the same issue, and its solution was simple - get rid of margins (or paddings, can't remember😅)

2022-03-29 04:47 UTC, jstmpelowycz commented on src/components/Carousel.tsx
> +              >
```suggestion
              <li key={image}>
```

2022-03-29 04:51 UTC, jstmpelowycz commented on src/components/Carousel.tsx
> +              >
Okay, that's a matter of taste to write it so, I won't mind it

2022-03-29 04:51 UTC, jstmpelowycz commented on src/components/Controller.tsx
> +
```suggestion
```

2022-03-29 04:53 UTC, jstmpelowycz commented on src/components/Controller.tsx
> +      </label>
Looks like repeating yourself, I would create a separate component

2022-03-29 04:56 UTC, jstmpelowycz approved these changes
A few meaningful suggestions, good job though 🚀

2022-03-29 14:19 UTC, solaryasha requested changes

2022-03-29 14:19 UTC, solaryasha commented on src/components/Carousel.tsx
> +    itemWidth: 140,
Таке саме питання, як і у  Діми, чому саме 140 ?

2022-03-29 14:19 UTC, solaryasha commented on src/components/Controller.tsx
> +      </label>
Погоджуюся, вдалий коментар, давай його виправимо

2022-03-30 12:10 UTC, solaryasha approved these changes
Обгорни функціональні компоненти в react.memo

2026-05-02 10:22 UTC, closed without merging