Solution
mate-academy/react_carousel pull request #157
Opened 2022-05-10 08:52 UTC by YegorKochetkov

[DEMO LINK](https://YegorKochetkov.github.io/react_carousel/)

2022-05-13 13:32 UTC, Yurii837 approved these changes
Хоть я не делал это задание  - работает класно и код по-моему ок.

2022-05-16 07:19 UTC, MaksimusCRS requested changes
Review your project, other people must understand it, i can`t understand your logic. This code unsupportable.

But works good 🔥

2022-05-16 07:19 UTC, MaksimusCRS commented on src/App.tsx
> +    if (!this.state.settings.isAnimation && !this.state.settings.isInfinite) {
Add separate variable and name it correctly

2022-05-16 07:19 UTC, MaksimusCRS commented on src/App.tsx
> +      && this.state.images.length === defaultLength) {
Here also

2022-05-16 07:19 UTC, MaksimusCRS commented on src/App.tsx
> +    if (this.state.settings.isInfinite && !this.state.settings.isScrollLeft) {
And here

2022-05-16 12:21 UTC, MaksimusCRS requested changes
Review again

2022-05-16 13:26 UTC, YegorKochetkov commented on src/App.tsx
> +                    Number(target.value)))
I'm sorry but I don't understand what is required of me

2022-05-17 07:04 UTC, MaksimusCRS approved these changes
🔥

2025-04-25 20:28 UTC, closed without merging