added carousel
mate-academy/react_carousel pull request #193
Opened 2022-08-09 15:17 UTC by silchyn

[DEMO](https://silchyn.github.io/react_carousel/)

2022-08-10 06:57 UTC, ivan-kadykalo requested changes

2022-08-10 06:57 UTC, ivan-kadykalo commented on src/components/Carousel.tsx
> +              .map((image, i) => (
```suggestion
            images.map((image, i) => (
```

2022-08-10 06:57 UTC, ivan-kadykalo commented on src/App.tsx
> +    }
🤯 Avoid nested ifs and use switch case

2022-08-10 09:29 UTC, silchyn commented on src/App.tsx
> +    }
> 🤯 Avoid nested ifs and use switch case

But how to use switch case with .contains()?

2022-08-10 09:39 UTC, ivan-kadykalo commented on src/App.tsx
> +    }
May google be with you🙃

<img width="639" alt="image" src="https://user-images.githubusercontent.com/57747481/183869107-ff48cdb4-571d-418b-a728-833ad9dbf05e.png">

2022-08-10 09:42 UTC, ivan-kadykalo requested changes
Fix switch case

2022-08-10 09:42 UTC, ivan-kadykalo commented on src/components/Carousel.tsx
> +          return { position: Math.max(0, state.position - props.step) };
```suggestion
          return (props.infinite && !state.position) 
          	? { position: props.images.length - props.frameSize }
          	: { position: Math.max(0, state.position - props.step) };
```

2022-08-10 09:43 UTC, silchyn commented on src/App.tsx
> +    }
> May google be with you🙃
> 
> <img alt="image" width="639" src="https://user-images.githubusercontent.com/57747481/183869107-ff48cdb4-571d-418b-a728-833ad9dbf05e.png">

Yeah, I know about that kludge but why it is better than if-else-if?

2022-08-10 09:49 UTC, ivan-kadykalo commented on src/App.tsx
> +    }
Switch case is more readable and works faster than if else.

2022-08-10 09:50 UTC, ivan-kadykalo commented on src/App.tsx
> +    }
It is not a better solution each time, but in this case it is.

2022-08-10 12:32 UTC, Ihor-Karpyn approved these changes

2022-11-25 08:38 UTC, ivan-kadykalo approved these changes

2023-02-10 20:09 UTC, closed without merging