solution
mate-academy/react_carousel pull request #204
Opened 2022-09-05 15:53 UTC by tiserett

[DEMO LINK](https://tiserett.github.io/react_carousel/)

2022-09-05 19:58 UTC, sergii-nosachenko requested changes
Maks, I've found some mistakes and bugs 🐛🐞🐜
Sorry, but you need to fix it.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/App.tsx
> +  animationDuration?: number;
These properties are not optional. On line 14 you declare all of them as default state values for your component.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/components/Carousel.scss
> +}
```suggestion
  &__btn {
    display: flex;
    justify-content: center;
    align-items: center;
    padding: 10px 30px;
    border-radius: 20px;

    transition: transform 0.3s linear;
    
    &--prev,
    &--next {
      transform: scale(1.2);
    }
  }
}
```

Your BEM is bad, Maks, I'm judging you 😈
Use modifiers on your buttons.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/components/Carousel.tsx
> +    canMoveNext: true,
These default values don't prevent you against mistakes.
If you have only 3 items in total in 3 pieces frame you'll have next button active.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/components/Carousel.tsx
> +    }
I think you combine it in one setState call.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/components/Carousel.tsx
> +
Something wrong is going on inside your handlers. Look [here](https://i.imgur.com/hLZns3S.png) and [here](https://i.imgur.com/xuM6eUb.png). Try to play with options and window width to catch these bugs.

2022-09-05 19:58 UTC, sergii-nosachenko commented on src/components/Carousel.tsx
> +          Prev
It seems that you need to replace texts with arrows due the task condition.

2022-09-06 11:56 UTC, sergii-nosachenko requested changes
Code become better, but I found the source of your bugs.

2022-09-06 11:56 UTC, sergii-nosachenko commented on src/components/Carousel.tsx
> +
Maks, it seems I've found the reason of bugs. Inside your handlers you determine the values from current state and props and then set new values. But! A huge issue here is that React optimizes the process of rendering, so now you don't know what values will be calculated (state can change suddenly during your code execution).
I propose you to use setState with callback immediately after you get inside your handler:
```
handler = () => this.setState((state, props) => {
  // calculations
  
  return {
    // new state object
  }
})
```

Why this is important? You can read it [here](https://uk.reactjs.org/docs/react-component.html#setstate)
Briefly, you need better control over what's going on when you want to set state.

2022-09-06 14:08 UTC, sergii-nosachenko approved these changes
Well done 🔥

2022-09-07 08:11 UTC, danylo-onishchuk approved these changes
good job at all :)

2022-09-07 08:11 UTC, danylo-onishchuk commented on src/App.tsx
>          {/* eslint-disable-next-line */}
?

2024-03-09 11:07 UTC, closed without merging