Solution
mate-academy/react_carousel pull request #247
Opened 2022-11-21 17:57 UTC by Ivanenko1402

[DEMO LINK](https://Ivanenko1402.github.io/react_carousel/)

2022-11-22 15:39 UTC, loralevitska requested changes
almost done! need some improvements

1. when I turn on the infinitive setting, I don't see the last emoji 

https://user-images.githubusercontent.com/70009205/203354236-c49f5558-a0e1-40a9-b247-2b9ae3e72f60.mov

2022-11-22 15:39 UTC, loralevitska commented on src/components/Carousel.scss
> +  background-color: yellowgreen;
it's good practice move all colors to variables

2022-11-22 15:39 UTC, loralevitska commented on src/components/Carousel.tsx
> +          (this.props.images.length - frameSize) * itemWidth);
such a record is not obvious, try to divide operations into variables

```suggestion
        // myVariable = this.props.images.length - frameSize
        this.newPosition = -(myVariable * itemWidth);
```

2022-11-22 15:39 UTC, loralevitska commented on src/components/Carousel.tsx
> +    this.newPosition = currentPosition - itemWidth * step;
```suggestion
    this.newPosition = currentPosition - (itemWidth * step);
```

2022-11-22 15:39 UTC, loralevitska commented on src/components/Carousel.tsx
> +      (this.props.images.length - frameSize) * itemWidth)) {
same here) try to simplify and change your code style to more readability. Please improve your code according this comment not only in these line but on whole your solution

2022-11-23 11:44 UTC, Anastasiia-Svintsova approved these changes

2026-03-02 13:35 UTC, closed without merging