did the task
mate-academy/react_carousel pull request #320
Opened 2023-03-02 09:11 UTC by vanyachyzh

[DEMO LINK](https://vanyachyzh.github.io/react_carousel/)

2023-03-02 09:21 UTC, OlEzhA0 requested changes
hey! please add isFinite checkbox to demo)

2023-03-02 09:21 UTC, OlEzhA0 commented on src/components/Carousel/Carousel.tsx
> +  swipe = (direction: string) => {
would be better to type it like
```suggestion
  swipe = (direction: 'prev' | 'next') => {
```

2023-03-02 09:21 UTC, OlEzhA0 commented on src/components/Carousel/Carousel.tsx
> +
where is checkbox for isFinite property ?)

2023-03-02 09:21 UTC, OlEzhA0 commented on src/components/Carousel/Carousel.tsx
> +                  style={{ width: `${itemWidth}px` }}
you can pass just number value
```suggestion
                  style={{ width: itemWidth }}
```

2023-03-02 11:26 UTC, Anastasiia-Svintsova requested changes
- Here should be shown default values 
<img width="518" alt="image" src="https://user-images.githubusercontent.com/99403198/222414580-6687e85d-c73e-451c-8494-752bf96d8b18.png">

- Would be great to add a min value for all input. See some examples below

https://user-images.githubusercontent.com/99403198/222414890-64b58d2a-6a05-42ae-afa6-a021150f3f73.mov

https://user-images.githubusercontent.com/99403198/222415224-d5b68293-e19d-4191-b760-b82d7d9024e0.mov

- You should disable buttons if the user can't scroll anymore 

https://user-images.githubusercontent.com/99403198/222415534-28d0d73e-0fc1-48f4-9cad-06b0b20f9376.mov

2023-03-04 14:40 UTC, VitaliyBondarenko1982 approved these changes

2024-03-07 18:38 UTC, closed without merging