init
mate-academy/react_carousel pull request #495
Opened 2023-08-30 09:37 UTC by MaksymKos

https://maksymkos.github.io/react_carousel/

2023-08-30 09:55 UTC, anastasiiavorobiova requested changes
Great work! 
<img width="215" alt="Screenshot 2023-08-30 at 12 52 34" src="https://github.com/mate-academy/react_carousel/assets/135232001/e59a5321-c941-489a-a597-7b72c53efc73">
Item width doesn't work correctly. Consider fixing it

2023-08-30 10:34 UTC, IvanFesenko requested changes
Check this case and fix it
https://github.com/mate-academy/react_carousel/assets/61904995/f697d3c5-4973-43ab-bf2e-c6ff9cf3454a

Infinite scroll do not works on frame size 7+
https://github.com/mate-academy/react_carousel/assets/61904995/13eed08f-0292-4109-8f4a-3d5ceb940262

2023-08-31 10:13 UTC, loralevitska requested changes
Almost everything is perfect) when the "next" button is pressed, the 7th picture cannot be seen, it seems to jump and does not fall into the frame at step 3
https://github.com/mate-academy/react_carousel/assets/70009205/32afcdc9-05ad-434d-a912-c6fc73e5d800

2023-08-31 10:13 UTC, loralevitska commented on src/App.scss
> +
Remove extra empty lines

2023-08-31 10:13 UTC, loralevitska commented on src/components/Carousel.scss
> +  color: #FFFFFF;
It is a good practice to make all colors [variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties)

2023-08-31 10:13 UTC, loralevitska commented on src/components/Carousel.tsx
> +              }}
Move to variable

2023-08-31 10:13 UTC, loralevitska commented on src/components/Carousel.tsx
> +            || params.frameSize === images.length}
Long expression move to variable. Fix all cases

2023-08-31 10:45 UTC, VitaliyBodnar requested changes
- All tests are not passed
<img width="589" alt="Screenshot 2023-08-31 at 13 45 14" src="https://github.com/mate-academy/react_carousel/assets/64746943/4fb5e867-c20c-4a2b-987d-c37652443495">

2023-08-31 10:47 UTC, MaksymKos commented
u can fix tests and after write it)

2023-08-31 12:05 UTC, IvanFesenko requested changes
Why step for size is 130?  What is that?
https://github.com/mate-academy/react_carousel/assets/61904995/03205f67-97ef-4ac3-bd07-18b986dfe383

2023-08-31 17:30 UTC, TarasHoliuk requested changes
GJ :-1: 
Fix Lint errors

2023-08-31 17:30 UTC, TarasHoliuk commented on src/components/Carousel.scss
> +  font-family: 'Courier New', Courier, monospace;
It's not critical issues, but on the other hand there are some lint rules, so we shouldn't ignore them
It's easy to fix - please, do it :)
![image](https://github.com/mate-academy/react_carousel/assets/86923089/5b3d8ed0-2456-43e8-a3cb-5431c9d1d620)

2023-08-31 18:08 UTC, etojeDenys approved these changes
good job

2023-08-31 18:08 UTC, etojeDenys commented on src/App.tsx
> +  return [...img].slice(firstImgIndex);
slice return the new array, so copying the array is redundant here

2024-10-14 06:30 UTC, closed without merging