commit
mate-academy/react_carousel pull request #496
Opened 2023-08-30 12:38 UTC by anastasia-radchencko

https://anastasia-radchencko.github.io/react_carousel/

2023-08-30 16:42 UTC, etojeDenys requested changes
let's add some min and max limits to inputs
<img width="444" alt="image" src="https://github.com/mate-academy/react_carousel/assets/70220667/18c1af19-9605-46a3-86a7-d255b42f91c6">

2023-08-30 16:42 UTC, etojeDenys commented on src/components/Carousel.tsx
> +          onClick={() => handleNextImage()}
```suggestion
          onClick={handleNextImage}
```
we can simplify it

2023-09-04 12:20 UTC, VitaliyBodnar requested changes
- all tests are not passed 
![Screenshot 2023-09-04 at 15 20 12](https://github.com/mate-academy/react_carousel/assets/64746943/00a856d2-67ac-4406-b122-af28397e4949)

2023-09-04 12:20 UTC, VitaliyBodnar commented on src/components/Carousel.tsx
> +          {'<<'}
```suggestion
          <<
```

2023-09-04 12:20 UTC, VitaliyBodnar commented on src/components/Carousel.tsx
> +          onClick={() => handlePrevImage()}
```suggestion
          onClick={handlePrevImage}
```

2023-09-04 12:20 UTC, VitaliyBodnar commented on src/components/Carousel.tsx
> +          {'>>'}
```suggestion
          >>
```

2023-09-04 12:20 UTC, VitaliyBodnar commented on src/App.tsx
> +  const [animationDuration, setAnimationDuration] = useState(1000);
make sense to move theses default values to enum, as it will make a code cleaner

2023-09-04 12:25 UTC, anastasia-radchencko commented on src/components/Carousel.tsx
> +          {'>>'}
![image](https://github.com/mate-academy/react_carousel/assets/115778975/a8fef261-fd50-4a13-acb8-73a85f7eb20b)

2023-09-04 15:05 UTC, closed without merging