add task solution
mate-academy/react_carousel pull request #518
Opened 2023-09-14 17:47 UTC by andrew17752985

https://andrew17752985.github.io/react_carousel/

2023-09-15 05:52 UTC, volodymyr-soltys97 requested changes
The task is not completely completed and it is not working
<img width="505" alt="image" src="https://github.com/mate-academy/react_carousel/assets/64750958/d2bafa0a-c4d0-4773-8e54-1c9d49388a6d">

2023-09-17 10:25 UTC, TarasHoliuk requested changes
If you have more questions feel free to ask in the chat

2023-09-17 10:25 UTC, TarasHoliuk commented on src/App.tsx
> +        images
use string template in such cases

2023-09-17 10:25 UTC, TarasHoliuk commented on src/components/Carousel.scss
> +  cursor: not-allowed;
in my case it just disappeared - just show common cursor

2023-09-17 10:25 UTC, TarasHoliuk commented on src/components/Carousel.scss
> +button {
do not add styles with tag selector

2023-09-17 10:25 UTC, TarasHoliuk commented on src/components/Carousel.scss
> +button[data-cy="nextButton"] {
add corresponding class instead of using attribute selector

2023-09-17 10:25 UTC, TarasHoliuk commented on src/components/Carousel.tsx
> +  const visibleImages = images.slice(currentIndex, currentIndex + frameSize);
in case frame size is 3 you should always show 3 images (last 3 in this case):
![image](https://github.com/mate-academy/react_carousel/assets/86923089/82803447-767f-4d25-b7a1-1b4218ce9556)

2023-09-17 10:25 UTC, TarasHoliuk commented on src/components/Carousel.tsx
> +  animationDuration = 1000,
you should use it to change images smoothly on buttons click

2023-09-18 05:55 UTC, volodymyr-soltys97 requested changes
The slider now automatically switches to the last image, it needs to switch only when you click on the buttons, also try to add a smooth transition between images
<img width="1512" alt="image" src="https://github.com/mate-academy/react_carousel/assets/64750958/62cdcb1f-10ef-4355-9144-bb0aa9e6c461">

2023-10-31 15:25 UTC, closed without merging