stage-1
mate-academy/react_carousel pull request #557
Opened 2023-10-27 15:51 UTC by no4kar

[DEMO LINK](https://no4kar.github.io/react_carousel/)

2023-10-28 06:42 UTC, VitaliyBondarenko1982 requested changes
Looks good.
Please commit and push all files with changes.
Tests can't resolve module classnames because package.json file wasn't committed and pushed
![Screenshot from 2023-10-28 09-37-31](https://github.com/mate-academy/react_carousel/assets/33029864/c032853c-c485-4cab-96b8-7c2bd38b3b44)

2023-10-28 11:11 UTC, OleziO requested changes

2023-10-28 11:11 UTC, OleziO commented on src/App.tsx
> +      // }
Remove all comments from the code.

2023-10-29 09:01 UTC, Andriy-Shymkiv approved these changes

2025-04-22 17:08 UTC, closed without merging