added the attempt number one
mate-academy/react_carousel pull request #56
Opened 2021-01-19 15:05 UTC by MarchD

[DEMO LINK](https://MarchD.github.io/react_carousel/)

2021-01-19 16:02 UTC, AlexysUa approved these changes
Great work!

2021-01-19 16:02 UTC, AlexysUa commented on src/components/Carousel.js
> +            <li key={img}>
You can use the numeric key from the image name.
(ex. './img/1.png'.match(/\d/g).join(''))

2021-01-20 10:38 UTC, vsm2k17 requested changes
great work let's make it even better, add a form which will be controlling the props which you pass into the Carousel component.

2021-01-27 14:08 UTC, aionova approved these changes
Awesome!

2021-01-27 14:08 UTC, aionova commented on src/App.js
> +              onChange={this.handle}
```suggestion
              onChange={this.handleInputChange}
```

2024-01-08 07:02 UTC, closed without merging