Develop
mate-academy/react_carousel pull request #697
Opened 2024-03-20 20:58 UTC by BoGoBooM

[DEMO LINK](https://bogoboom.github.io/react_carousel/)

2024-03-21 07:55 UTC, maxim2310 requested changes
looks like broken 
![image](https://github.com/mate-academy/react_carousel/assets/96265844/a258468d-ac3b-43c5-a9b5-a851610d0819)

2024-03-25 17:11 UTC, Viktor-Kost requested changes

2024-03-25 17:11 UTC, Viktor-Kost commented on src/App.tsx
>    };
You can simplify this handler and reuse for each input by adding `name`s to your inputs (or you can take `id`)
```suggestion
  handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    const { id, value } = e.target;
    
    this.setState(prevState => ({
      ...prevState,
      [id]: +value,
    }));
  };
```

2024-03-25 17:12 UTC, Viktor-Kost requested changes
.

2024-03-25 18:33 UTC, SanyaBratashchuk requested changes

2024-03-25 18:33 UTC, SanyaBratashchuk commented on src/components/Carousel.tsx
> +            transition,
```suggestion
            transition: `transform ${transition}ms ease-in-out`,
```

2024-03-25 18:33 UTC, SanyaBratashchuk commented on src/components/Carousel.tsx
> +  const [transition, setTransition] = useState('transform 1000ms ease-in-out');
```suggestion
  const [transition, setTransition] = useState(1000);
```

2024-03-25 19:28 UTC, maxim2310 requested changes
Good work, but lets make some improvement 

1. firstly would be nice to add some minimum style for this 
2. increasing frame size break carousel
![image](https://github.com/mate-academy/react_carousel/assets/96265844/4fd590f9-ef76-4f68-adf0-d570818eb7ce)
3. also would be nice to fix merge conflict 
![image](https://github.com/mate-academy/react_carousel/assets/96265844/5d6e3a7b-ca4a-460c-8cfa-9c9c1f548af8)

2024-03-26 08:13 UTC, maxim2310 requested changes
Great job overall! Just one tiny thing needs to be fixed before approval)

still have this problem 
![image](https://github.com/mate-academy/react_carousel/assets/96265844/e638b1a8-5535-48f7-8161-1f5e1257d722)

2024-03-28 21:26 UTC, BoGoBooM commented
I don't know how I can fix this bug and how can I formulate a request on the platform to get help...
I also saw that other students have this bug

2024-03-29 07:47 UTC, maxim2310 approved these changes
So you can skip it but would be nice to fix, you just need to make check if your index + frame size > than quantity of imgs then make index - 1, or you can ask it in fe chat

2025-02-17 11:49 UTC, closed without merging