react_carousel
mate-academy/react_carousel pull request #723
Opened 2024-04-17 14:30 UTC by svyatoslavPy

[DEMO LINK](https://svyatoslavPy.github.io/react_carousel/)

2024-04-17 16:15 UTC, sTorba24 requested changes
Good work!  But you need some improvements

These settings should be changeable, use inputs etc
![image](https://github.com/mate-academy/react_carousel/assets/55200530/15e48d30-0e4f-46bc-9697-f3c0ec7f1d79)

2024-04-18 13:34 UTC, l4st1m0za requested changes
No changes are deployed

2024-04-18 14:33 UTC, sTorba24 requested changes
Good progress!

1. If there not enough items to scroll for full step count => scroll only count of images that available. Here shouldn't be 3 white spaces
![image](https://github.com/mate-academy/react_carousel/assets/55200530/f572f6fe-ac58-42a2-9dfa-2ae977904d56)

2. disable prev/next when you already scrolled to first/last item
![image](https://github.com/mate-academy/react_carousel/assets/55200530/b4c200ba-7d16-4e17-891c-f7bf03289918)

2024-04-18 14:33 UTC, sTorba24 commented on src/App.tsx
> +    step: 1,
3 by default

2024-04-19 09:32 UTC, volodymyr-soltys97 requested changes
Good job 👍 
Let's improve your code
Need to fix width
<img width="896" alt="image" src="https://github.com/mate-academy/react_carousel/assets/64750958/d96ff89d-bef1-4dca-bd41-5d9a87543db6">

Also need to remove list style for the tag li
<img width="154" alt="image" src="https://github.com/mate-academy/react_carousel/assets/64750958/612e4638-b3ab-4e83-99e4-119dc420e7fd">

2024-04-19 09:32 UTC, volodymyr-soltys97 commented on src/components/Carousel/Carousel.scss
> +  // }
Remove comments everywhere

2024-04-22 10:19 UTC, anastasiiavorobiova requested changes
Great work! Almost done!

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/App.tsx
>          <h1>Carousel with {images.length} images</h1>
```suggestion
        <h1 data-cy="title">Carousel with {images.length} images</h1>
```
Consider adding all needed data attributes to pass tests

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/components/CarouselSettings/CarouselSettings.scss
> +  box-shadow: 0px 2.31px 8.67px 0px $white-color;
```suggestion
  box-shadow: 0 2.31px 8.67px 0 $white-color;
```

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/components/CarouselSettings/CarouselSettings.scss
> +    box-shadow: 0px 2.31px 8.67px 0px $gray-color;
```suggestion
    box-shadow: 0 2.31px 8.67px 0 $gray-color;
```

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/components/Carousel/Carousel.tsx
> +                  alt="1"
```suggestion
                  alt="1"
                  width={itemWidth}
```

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/components/Carousel/Carousel.tsx
> +                    width: `${itemWidth}px`,
```suggestion

```

2024-04-22 10:19 UTC, anastasiiavorobiova commented on src/components/Carousel/Carousel.scss
Consider adding space between carousel images

2024-09-28 18:20 UTC, closed without merging